name: Seguridad-DIMAZ
on: [push]
jobs:
  analisis-y-construccion:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v3

      - name: Construir Imagen Docker
        # Aquí definimos el nombre 'monitor-pyme:v1'
        run: docker build -t monitor-pyme:v1 .

      - name: Escaneo de Seguridad (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          # Aquí usamos EXACTAMENTE el mismo nombre
          image-ref: 'monitor-pyme:v1'
          format: 'table'
          exit-code: '0' # Cámbialo a '0' para que el pipeline no falle si encuentra riesgos y puedas ver el reporte
          severity: 'CRITICAL,HIGH'
